import './globals.css'
import { Inter } from 'next/font/google'

//components
import Navbar from './components/navbar'
import Footer from './components/footer'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html  lang="en">
      
      
      <body className={inter.className} class="m-0 text-0 font-helvetica bg-gray-300 w-screen h-screen ">
      <Navbar/>
        {children}
        
        <Footer/>
        </body>
        
    </html>
  )
}
